### ISSUE TITLE
Naming sanity check

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#12]
#### What do you want to talk about?
When this repository was created, the scope of this service was a little bit more broad and directly related to the Permanent upload flow / use case.

At this point, it is actually a service that generates a URL (plus authentication metadata) that could then be used for a variety of processes.  `uploader-service` is now a little bit of a misnomer.

What do you think of renaming the repository to something like `destination-url-service`?

**Comment by xmunoz** [comment]
Please no `service` suffix. That is already a lot to type.

**Comment by jasonaowen** [comment]
Naming gets into what our vision for this repository is, which in turn is directly related to the architecture discussions we were having around https://github.com/PermanentOrg/meta/issues/1 .

We put that conversation on hold for because we weren't ready to commit to a specific path yet, but needed to make progress on resolving the upload issues. This repository, and our approach to integrating it with the rest of the application, struck a middle ground: it leaves us the flexibility to choose an architecture later, without binding us to any of proposed options; it minimizes the amount of new functionality we'd need to create in PHP; and it lets us focus on the specific issue of upload reliability without boiling the ocean.

I see the place we're now in as a step along a path to somewhere else. The fact that this does or will do a concrete, useful thing, independent of the rest of the Permanent application, is a nice side effect, but I don't think it's worth stopping here as a result. I don't think we're ready to resume our conversation around architecture yet, but am happy to hear if y'all disagree!

**Comment by slifty** [comment]
Sounds good to me!  Lets keep it with the current name and circle back.  I'll close this issue in a few days and we can re-visit when the time is right.

Side note, my personal preference / vision for this would be a `services` repository (monorepo, but not monolith) for these kinds of microservices.  This approach would allow us to share common linting, transpiling, testrunners, and other dev tools.  (and it would also have a nice succinct name!)

**Comment by xmunoz** [comment]
It has been decided. The deployment name is `node-uploader.service`, and the repo name will stay as `upload-service`.
