### ISSUE TITLE
SQS integration

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/upload-service#6]
#### Description
After an S3 token has been generated (#5), we need to announce the new file to SQS so that the rest of the system can properly respond to the upload and associate it with this particular user.

This issue is specifically about the SQS integration, not necessarily the business logic that will utilize SQS.

#### Relevant Resources / Research
- https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-send-receive-messages.html

**Comment by jasonaowen** [comment]
After discussing implementation approaches today, @slifty and I agreed that as a first step, we'll have the client (the JavaScript front-end or the mobile app) report upload success to the legacy API rather than create a new message queue, emit messages from this repo, and set up a listener elsewhere. It's maybe not where we want to be architecturally for the long term, but it allows us to get #5 out more quickly while still advancing along our intended path.

**Comment by slifty** [comment]
Given the above, I think it would be appropriate to close this issue -- SQS integration for this service is not a current part of the road map, and may never be.
